In [8]:
import cv2
import numpy as np

In [9]:
image_path = '../../dataset/Limes/113_100.jpg'
img_to_test = cv2.imread(image_path)
img_to_test

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [10]:
from preprocessing import converter_para_cinza
img_to_test_cinza = converter_para_cinza(img_to_test)
img_to_test_cinza

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], shape=(100, 100), dtype=uint8)

In [11]:
from preprocessing import aplicar_filtro_gaussiano
img_to_test_gaussiano = aplicar_filtro_gaussiano(img_to_test_cinza)
img_to_test_gaussiano

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], shape=(100, 100), dtype=uint8)

In [12]:
from segmentation import segmentar_objeto_com_flood_fill
img_to_test_mascara = segmentar_objeto_com_flood_fill(img_to_test_gaussiano)
img_to_test_mascara

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(100, 100), dtype=uint8)

In [13]:
from segmentation import encontrar_contornos
img_to_test_contornos = encontrar_contornos(img_to_test_mascara)
img_to_test_contornos

(array([[[45,  0]],
 
        [[45,  1]],
 
        [[44,  2]],
 
        [[43,  2]],
 
        [[42,  3]],
 
        [[40,  3]],
 
        [[39,  4]],
 
        [[37,  4]],
 
        [[36,  5]],
 
        [[34,  5]],
 
        [[33,  6]],
 
        [[32,  6]],
 
        [[31,  7]],
 
        [[30,  7]],
 
        [[28,  9]],
 
        [[27,  9]],
 
        [[23, 13]],
 
        [[22, 13]],
 
        [[19, 16]],
 
        [[19, 17]],
 
        [[14, 22]],
 
        [[14, 23]],
 
        [[13, 24]],
 
        [[13, 25]],
 
        [[12, 26]],
 
        [[12, 28]],
 
        [[11, 29]],
 
        [[11, 30]],
 
        [[10, 31]],
 
        [[10, 33]],
 
        [[ 8, 35]],
 
        [[ 8, 37]],
 
        [[ 7, 38]],
 
        [[ 7, 40]],
 
        [[ 6, 41]],
 
        [[ 6, 44]],
 
        [[ 5, 45]],
 
        [[ 5, 52]],
 
        [[ 4, 53]],
 
        [[ 4, 57]],
 
        [[ 3, 58]],
 
        [[ 3, 60]],
 
        [[ 4, 61]],
 
        [[ 4, 68]],
 
        [[ 5, 69]],
 
        [[

In [14]:
from geometric import calcular_area, calcular_perimetro, calcular_circularidade, calcular_aspect_ratio

for i, contorno in enumerate(img_to_test_contornos):
    area = calcular_area(contorno)
    perimetro = calcular_perimetro(contorno)
    circularidade = calcular_circularidade(contorno)
    aspect = calcular_aspect_ratio(contorno)
    
    print(f"\nContorno {i+1}:")
    print(f"  Área: {area:.2f} pixels")
    print(f"  Perímetro: {perimetro:.2f}")
    print(f"  Circularidade: {circularidade:.4f}")
    print(f"  Aspect Ratio: {aspect:.4f}")


Contorno 1:
  Área: 7335.00 pixels
  Perímetro: 324.25
  Circularidade: 0.8767
  Aspect Ratio: 0.9400
